"""รายละเอียดโปรโมชั่นแต่ละค่าย + คำแนะนำเสริม"""
SERVER_DETAILS = {
    "1": {
        "name": "AIS-VIP",
        "carrier": "AIS",
        "logo": "🇹🇭",
        "protocol": "VMESS · WebSocket · 80",
        "speed": "64Kbps - 128Kbps",
        "max_speed": "สูงสุด 10 Mbps",
        "devices": "1-2 เครื่อง",
        "price": "เริ่มต้น 50 บ./เดือน",
        "features": [
            "✅ รองรับ AIS 4G/5G ทุกคลื่น",
            "✅ ความเร็ว 64Kbps - 128Kbps (ไม่ลดสปีด)",
            "✅ ไม่จำกัด GB",
            "✅ เล่น Social Media, LINE, FB, TikTok",
            "✅ ใช้ร่วมกับ AIS PLAY ได้",
        ],
        "addons": [
            {
                "name": "สมัครโปรกันรั้ว (ใช้คู่กับ VPN)",
                "code": "*777*7068#",
                "price": "35 บาท/เดือน",
                "note": "กดสมัครเพื่อใช้งานคู่กับ VPN",
            },
            {
                "name": "สมัคร AISPLAY",
                "code": "*777*7310#",
                "price": "09.63 บาท / 1 วัน",
                "note": "กดสมัคร AISPLAY 1 วัน",
            },
        ],
        "compatible": ["TRUE", "DTAC", "TOT", "3BB"],
        "note": "เหมาะสำหรับใช้งานทั่วไป เล่นไลน์ เฟสบุ๊ค ติ๊กต๊อก ความเร็วสูงสุด 10 Mbps",
        "banner_style": "ais",
    },
    "2": {
        "name": "AIS-TCP",
        "carrier": "AIS",
        "logo": "🇹🇭",
        "protocol": "VMESS · TCP · 8080",
        "speed": "64Kbps - 128Kbps",
        "max_speed": "สูงสุด 10 Mbps",
        "devices": "1-2 เครื่อง",
        "price": "เริ่มต้น 50 บ./เดือน",
        "features": [
            "✅ รองรับ AIS 4G/5G ทุกคลื่น",
            "✅ TCP Protocol เสถียรกว่า",
            "✅ ความเร็ว 64Kbps - 128Kbps",
            "✅ ไม่จำกัด GB",
            "✅ เหมาะกับพื้นที่ AIS สัญญาณดี",
        ],
        "addons": [
            {
                "name": "สมัครโปรกันรั้ว (ใช้คู่กับ VPN)",
                "code": "*777*7068#",
                "price": "35 บาท/เดือน",
                "note": "กดสมัครเพื่อใช้งานคู่กับ VPN",
            },
        ],
        "compatible": ["TRUE", "DTAC", "TOT"],
        "note": "TCP Protocol เสถียร แต่ใช้ได้ดีในพื้นที่ AIS สัญญาณแรง ความเร็วสูงสุด 10 Mbps",
        "banner_style": "ais",
    },
    "3": {
        "name": "FB-GAMING",
        "carrier": "AIS/FB",
        "logo": "🇹🇭",
        "protocol": "VMESS · TLS · 8000",
        "speed": "สูงสุด 128Kbps",
        "max_speed": "สูงสุด 10 Mbps",
        "devices": "1-2 เครื่อง",
        "price": "เริ่มต้น 50 บ./เดือน",
        "features": [
            "✅ รองรับ AIS 4G/5G",
            "✅ TLS Encryption ป้องกัน DPI",
            "✅ ความเร็วสูง เล่นเกมได้",
            "✅ เล่น Social Media ได้ปกติ",
            "✅ ไม่จำกัด GB",
            "✅ เหมาะกับเกมและสตรีมมิ่ง",
        ],
        "addons": [
            {
                "name": "สมัครโปรกันรั้ว (ใช้คู่กับ VPN)",
                "code": "*777*7068#",
                "price": "35 บาท/เดือน",
                "note": "กดสมัครเพื่อใช้งานคู่กับ VPN",
            },
        ],
        "compatible": ["TRUE", "DTAC"],
        "note": "TLS Encryption ช่วยเลี่ยง DPI ได้ดี เล่นเกมลื่น ความเร็วสูงสุด 10 Mbps",
        "banner_style": "fb",
    },
    "4": {
        "name": "TRUE VLESS",
        "carrier": "TRUE",
        "logo": "🇹🇭",
        "protocol": "VLESS · WebSocket · 2053",
        "speed": "64Kbps - 128Kbps",
        "max_speed": "สูงสุด 10 Mbps",
        "devices": "1-2 เครื่อง",
        "price": "เริ่มต้น 50 บ./เดือน",
        "features": [
            "✅ รองรับ TRUE 4G/5G ทุกคลื่น",
            "✅ VLESS Protocol ล่าสุด",
            "✅ ความเร็ว 64Kbps - 128Kbps",
            "✅ เล่น Social Media ได้ปกติ",
            "✅ ไม่จำกัด GB",
            "✅ ใช้กับ TRUE WiFi ได้",
        ],
        "addons": [],
        "compatible": ["AIS", "DTAC"],
        "note": "VLESS Protocol ทันสมัย เหมาะกับ TRUE โดยเฉพาะ ความเร็วสูงสุด 10 Mbps",
        "banner_style": "true",
    },
}
